languageCode = "en"
hasCJKLanguage = true 
languageName = "English"
weight = 1
title = "迷途小书童"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "Mon Jan 2 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "迷途小书童's Blog."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "《临江仙·滚滚长江东逝水》"
  #image = "img/blowfish_logo.png"
  headline = "明·杨慎"  